In [1]:
import pandas as pd
from openai import OpenAI
from sqlalchemy import create_engine, Column, String, MetaData, Table
from pgvector.sqlalchemy import Vector
import os
from dotenv import load_dotenv

load_dotenv()
client = OpenAI(api_key=os.getenv("OPENAI_API_KEY"))
# CSV 읽기
df = pd.read_csv("./국토교통부_전국 법정동_20250415.csv")

# 조건 1: 시군구명은 NaN이 아니고, 읍면동명은 NaN
filtered_df = df[df["읍면동명"].isna()]

# 시도 코드 / 시군구 코드 추출
filtered_df["시도코드"] = filtered_df["법정동코드"].astype(str).str[:2]
filtered_df["시군구코드"] = filtered_df["법정동코드"].astype(str).str[2:5]

# 조건 2: 서울, 부산, 제주, 인천, 강릉만 남기기
keep_sido = ["서울특별시", "부산광역시", "제주특별자치도", "인천광역시"]
keep_sigungu = ["강릉시"]

final_df = filtered_df[
    (filtered_df["시도명"].isin(keep_sido)) |
    (filtered_df["시군구명"].isin(keep_sigungu))
]
# print(final_df)
# 시도명과 시군구명 합치기
final_df["시도_시군구"] = final_df["시도명"].fillna("") + " " + final_df["시군구명"].fillna("")

# 필요한 컬럼 순서대로 재배치
final_df = final_df[["시도코드", "시군구코드", "시도_시군구"]]

final_df = final_df.reset_index(drop=True)
print(final_df)

   시도코드 시군구코드        시도_시군구
0    11   000        서울특별시
1    11   110     서울특별시 종로구
2    11   140      서울특별시 중구
3    11   170     서울특별시 용산구
4    11   200     서울특별시 성동구
..  ...   ...           ...
60   42   150       강원도 강릉시
61   50   000      제주특별자치도
62   50   110   제주특별자치도 제주시
63   50   130  제주특별자치도 서귀포시
64   51   150   강원특별자치도 강릉시

[65 rows x 3 columns]

/tmp/ipykernel_780/3784374850.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_df["시도코드"] = filtered_df["법정동코드"].astype(str).str[:2]
/tmp/ipykernel_780/3784374850.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_df["시군구코드"] = filtered_df["법정동코드"].astype(str).str[2:5]
/tmp/ipykernel_780/3784374850.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_df["시도_시군구"] = final_df["시도명"].fillna("") + " " + final_df["시군구명"].fillna("")

In [3]:
from sqlalchemy import create_engine, MetaData, Table, Column, String
from pgvector.sqlalchemy import Vector

engine = create_engine("postgresql+psycopg2://postgres:1234@localhost:5432/postgres")

metadata = MetaData()

embeddings = []
for text in final_df["시도_시군구"]:
    response = client.embeddings.create(
        model="text-embedding-3-small",
        input=text
    )
    embeddings.append(response.data[0].embedding)

dimension = len(embeddings[0])

table = Table(
    "city_regions",
    metadata,
    Column("city_code1", String),
    Column("city_code2", String),
    Column("city_str", String),
    Column("embedding", Vector(dimension))
)

metadata.create_all(engine)

# 5. 데이터 삽입
with engine.connect() as conn:
    for i, row in final_df.iterrows():
        print(i, row)
        # conn.execute(
        #     table.insert().values(
        #         city_code1=row["city_code1"],
        #         city_code2=row["city_code2"],
        #         city_str=row["city_str"],
        #         embedding=embeddings[i]
        #     )
        # )

0 시도코드          11
시군구코드        000
시도_시군구    서울특별시
Name: 0, dtype: object
1 시도코드             11
시군구코드           110
시도_시군구    서울특별시 종로구
Name: 1, dtype: object
2 시도코드            11
시군구코드          140
시도_시군구    서울특별시 중구
Name: 2, dtype: object
3 시도코드             11
시군구코드           170
시도_시군구    서울특별시 용산구
Name: 3, dtype: object
4 시도코드             11
시군구코드           200
시도_시군구    서울특별시 성동구
Name: 4, dtype: object
5 시도코드             11
시군구코드           215
시도_시군구    서울특별시 광진구
Name: 5, dtype: object
6 시도코드              11
시군구코드            230
시도_시군구    서울특별시 동대문구
Name: 6, dtype: object
7 시도코드             11
시군구코드           260
시도_시군구    서울특별시 중랑구
Name: 7, dtype: object
8 시도코드             11
시군구코드           290
시도_시군구    서울특별시 성북구
Name: 8, dtype: object
9 시도코드             11
시군구코드           305
시도_시군구    서울특별시 강북구
Name: 9, dtype: object
10 시도코드             11
시군구코드           320
시도_시군구    서울특별시 도봉구
Name: 10, dtype: object
11 시도코드             11
시군구코드           350
시도_시군구    서울특별시 노원구
Name: 11, dtype: object
12 시도코드             11
시군구코드           380
시도_시군구    서울특별시 은평구
Name: 12, dtype: object
13 시도코드              11
시군구코드            410
시도_시군구    서울특별시 서대문구
Name: 13, dtype: object
14 시도코드             11
시군구코드           440
시도_시군구    서울특별시 마포구
Name: 14, dtype: object
15 시도코드             11
시군구코드           470
시도_시군구    서울특별시 양천구
Name: 15, dtype: object
16 시도코드             11
시군구코드           500
시도_시군구    서울특별시 강서구
Name: 16, dtype: object
17 시도코드             11
시군구코드           530
시도_시군구    서울특별시 구로구
Name: 17, dtype: object
18 시도코드             11
시군구코드           545
시도_시군구    서울특별시 금천구
Name: 18, dtype: object
19 시도코드              11
시군구코드            560
시도_시군구    서울특별시 영등포구
Name: 19, dtype: object
20 시도코드             11
시군구코드           590
시도_시군구    서울특별시 동작구
Name: 20, dtype: object
21 시도코드             11
시군구코드           620
시도_시군구    서울특별시 관악구
Name: 21, dtype: object
22 시도코드             11
시군구코드           650
시도_시군구    서울특별시 서초구
Name: 22, dtype: object
23 시도코드             11
시군구코드           680
시도_시군구    서울특별시 강남구
Name: 23, dtype: object
24 시도코드             11
시군구코드           710
시도_시군구    서울특별시 송파구
Name: 24, dtype: object
25 시도코드             11
시군구코드           740
시도_시군구    서울특별시 강동구
Name: 25, dtype: object
26 시도코드          26
시군구코드        000
시도_시군구    부산광역시
Name: 26, dtype: object
27 시도코드            26
시군구코드          110
시도_시군구    부산광역시 중구
Name: 27, dtype: object
28 시도코드            26
시군구코드          140
시도_시군구    부산광역시 서구
Name: 28, dtype: object
29 시도코드            26
시군구코드          170
시도_시군구    부산광역시 동구
Name: 29, dtype: object
30 시도코드             26
시군구코드           200
시도_시군구    부산광역시 영도구
Name: 30, dtype: object
31 시도코드              26
시군구코드            230
시도_시군구    부산광역시 부산진구
Name: 31, dtype: object
32 시도코드             26
시군구코드           260
시도_시군구    부산광역시 동래구
Name: 32, dtype: object
33 시도코드            26
시군구코드          290
시도_시군구    부산광역시 남구
Name: 33, dtype: object
34 시도코드            26
시군구코드          320
시도_시군구    부산광역시 북구
Name: 34, dtype: object
35 시도코드              26
시군구코드            350
시도_시군구    부산광역시 해운대구
Name: 35, dtype: object
36 시도코드             26
시군구코드           380
시도_시군구    부산광역시 사하구
Name: 36, dtype: object
37 시도코드             26
시군구코드           410
시도_시군구    부산광역시 금정구
Name: 37, dtype: object
38 시도코드             26
시군구코드           440
시도_시군구    부산광역시 강서구
Name: 38, dtype: object
39 시도코드             26
시군구코드           470
시도_시군구    부산광역시 연제구
Name: 39, dtype: object
40 시도코드             26
시군구코드           500
시도_시군구    부산광역시 수영구
Name: 40, dtype: object
41 시도코드             26
시군구코드           530
시도_시군구    부산광역시 사상구
Name: 41, dtype: object
42 시도코드             26
시군구코드           710
시도_시군구    부산광역시 기장군
Name: 42, dtype: object
43 시도코드          28
시군구코드        000
시도_시군구    인천광역시
Name: 43, dtype: object
44 시도코드            28
시군구코드          110
시도_시군구    인천광역시 중구
Name: 44, dtype: object
45 시도코드                28
시군구코드              115
시도_시군구    인천광역시 중구영종출장
Name: 45, dtype: object
46 시도코드                28
시군구코드              116
시도_시군구    인천광역시 중구용유출장
Name: 46, dtype: object
47 시도코드            28
시군구코드          140
시도_시군구    인천광역시 동구
Name: 47, dtype: object
48 시도코드            28
시군구코드          170
시도_시군구    인천광역시 남구
Name: 48, dtype: object
49 시도코드              28
시군구코드            177
시도_시군구    인천광역시 미추홀구
Name: 49, dtype: object
50 시도코드             28
시군구코드           185
시도_시군구    인천광역시 연수구
Name: 50, dtype: object
51 시도코드             28
시군구코드           200
시도_시군구    인천광역시 남동구
Name: 51, dtype: object
52 시도코드            28
시군구코드          230
시도_시군구    인천광역시 북구
Name: 52, dtype: object
53 시도코드                28
시군구코드              235
시도_시군구    인천광역시 북구계양출장
Name: 53, dtype: object
54 시도코드             28
시군구코드           237
시도_시군구    인천광역시 부평구
Name: 54, dtype: object
55 시도코드             28
시군구코드           245
시도_시군구    인천광역시 계양구
Name: 55, dtype: object
56 시도코드            28
시군구코드          260
시도_시군구    인천광역시 서구
Name: 56, dtype: object
57 시도코드                28
시군구코드              265
시도_시군구    인천광역시 서구검단출장
Name: 57, dtype: object
58 시도코드             28
시군구코드           710
시도_시군구    인천광역시 강화군
Name: 58, dtype: object
59 시도코드             28
시군구코드           720
시도_시군구    인천광역시 옹진군
Name: 59, dtype: object
60 시도코드           42
시군구코드         150
시도_시군구    강원도 강릉시
Name: 60, dtype: object
61 시도코드            50
시군구코드          000
시도_시군구    제주특별자치도
Name: 61, dtype: object
62 시도코드               50
시군구코드             110
시도_시군구    제주특별자치도 제주시
Name: 62, dtype: object
63 시도코드                50
시군구코드              130
시도_시군구    제주특별자치도 서귀포시
Name: 63, dtype: object
64 시도코드               51
시군구코드             150
시도_시군구    강원특별자치도 강릉시
Name: 64, dtype: object

In [4]:
# from sqlalchemy import insert

# with engine.connect() as conn:
#     for (idx, row), embedding in zip(final_df.iterrows(), embeddings):
#         stmt = insert(table).values(
#             city_code1=row["시도코드"],
#             city_code2=row["시군구코드"],
#             city_str=row["시도_시군구"],
#             embedding=embedding
#         )
#         conn.execute(stmt)
#     conn.commit()

In [5]:
with engine.connect() as conn:
    result = conn.execute(table.select())
    for row in result:
        print(row)

engine.url

('11', '000', '서울특별시 ', array([-0.00659805, -0.04303442,  0.01832325, ...,  0.00422126,
       -0.02388933, -0.0269899 ], shape=(1536,), dtype=float32))
('11', '110', '서울특별시 종로구', array([ 0.00055065, -0.00335936,  0.0020389 , ..., -0.0191235 ,
       -0.01945746, -0.00555425], shape=(1536,), dtype=float32))
('11', '140', '서울특별시 중구', array([ 0.00986113, -0.03281726,  0.00464704, ..., -0.01270517,
       -0.04146458, -0.04624895], shape=(1536,), dtype=float32))
('11', '170', '서울특별시 용산구', array([ 0.01824048, -0.03199277,  0.0034141 , ...,  0.00174061,
       -0.01034778, -0.00957098], shape=(1536,), dtype=float32))
('11', '200', '서울특별시 성동구', array([ 0.03929863, -0.03675556, -0.01864306, ...,  0.01073943,
       -0.02940079, -0.00168318], shape=(1536,), dtype=float32))
('11', '215', '서울특별시 광진구', array([-0.01918794, -0.02347595, -0.0076977 , ..., -0.02414257,
       -0.01771056, -0.01866545], shape=(1536,), dtype=float32))
('11', '230', '서울특별시 동대문구', array([ 0.01463334, -0.05049583,  0.00586144, ...,  0.00512257,
       -0.01405665, -0.02128322], shape=(1536,), dtype=float32))
('11', '260', '서울특별시 중랑구', array([ 0.0097308 , -0.04775177,  0.02208162, ..., -0.00057727,
       -0.02760713, -0.01904362], shape=(1536,), dtype=float32))
('11', '290', '서울특별시 성북구', array([ 0.01291094, -0.02145534, -0.03369242, ...,  0.00775824,
       -0.02438433, -0.03191346], shape=(1536,), dtype=float32))
('11', '305', '서울특별시 강북구', array([-0.01274128, -0.06038064,  0.00886272, ..., -0.02057863,
       -0.0133565 , -0.01993667], shape=(1536,), dtype=float32))
('11', '320', '서울특별시 도봉구', array([ 0.03931615, -0.02746505,  0.00034459, ...,  0.01443079,
        0.00675474, -0.0128403 ], shape=(1536,), dtype=float32))
('11', '350', '서울특별시 노원구', array([ 0.00145231, -0.04032017,  0.01811199, ..., -0.03209002,
       -0.01121263, -0.0100706 ], shape=(1536,), dtype=float32))
('11', '380', '서울특별시 은평구', array([ 0.02047926, -0.05227694,  0.01495269, ..., -0.00505792,
       -0.03639578, -0.02085065], shape=(1536,), dtype=float32))
('11', '410', '서울특별시 서대문구', array([ 0.00825975, -0.04413567,  0.02301796, ...,  0.00018991,
       -0.02355576, -0.02710526], shape=(1536,), dtype=float32))
('11', '440', '서울특별시 마포구', array([-0.0121159 , -0.04002734, -0.0162712 , ...,  0.02039061,
       -0.03963244, -0.01864951], shape=(1536,), dtype=float32))
('11', '470', '서울특별시 양천구', array([ 0.00551807, -0.03153185, -0.01630007, ..., -0.026087  ,
       -0.02289936, -0.02110738], shape=(1536,), dtype=float32))
('11', '500', '서울특별시 강서구', array([-0.00306549, -0.02269034,  0.05846246, ...,  0.00879317,
       -0.04351186, -0.01722492], shape=(1536,), dtype=float32))
('11', '530', '서울특별시 구로구', array([-0.00651401, -0.0473007 ,  0.02539533, ..., -0.01182518,
       -0.00412314, -0.01589114], shape=(1536,), dtype=float32))
('11', '545', '서울특별시 금천구', array([-0.01306912, -0.01966182, -0.00193443, ..., -0.03263254,
       -0.00848911, -0.02388401], shape=(1536,), dtype=float32))
('11', '560', '서울특별시 영등포구', array([ 0.00320014, -0.04969631,  0.00299583, ...,  0.02479306,
       -0.01540843, -0.01382902], shape=(1536,), dtype=float32))
('11', '590', '서울특별시 동작구', array([-0.00151449, -0.01395015,  0.01210599, ..., -0.00070333,
       -0.0034107 , -0.00566136], shape=(1536,), dtype=float32))
('11', '620', '서울특별시 관악구', array([ 0.00495136, -0.01243326,  0.00931763, ...,  0.00935176,
        0.00250859,  0.00437358], shape=(1536,), dtype=float32))
('11', '650', '서울특별시 서초구', array([ 0.00666125, -0.02936503,  0.01322999, ...,  0.0020111 ,
       -0.02838434, -0.01406265], shape=(1536,), dtype=float32))
('11', '680', '서울특별시 강남구', array([-0.0069572 ,  0.00133056,  0.03026382, ...,  0.01581023,
       -0.02241957, -0.03295973], shape=(1536,), dtype=float32))
('11', '710', '서울특별시 송파구', array([ 0.00845414, -0.03560554,  0.01125482, ..., -0.02124174,
        0.00050287, -0.02516704], shape=(1536,), dtype=float32))
('11', '740', '서울특별시 강동구', array([ 0.01543599, -0.02706608,  0.0063461 , ...,  0.01049718,
       -0.03979369, -0.01133802], shape=(1536,), dtype=float32))
('26', '000', '부산광역시 ', array([-0.00578418,  0.0155829 ,  0.0421881 , ...,  0.02766698,
       -0.02621083,  0.00075526], shape=(1536,), dtype=float32))
('26', '110', '부산광역시 중구', array([-0.01178953,  0.01641325,  0.0349561 , ...,  0.00864789,
       -0.04953713, -0.01775624], shape=(1536,), dtype=float32))
('26', '140', '부산광역시 서구', array([-0.00512451,  0.01727557,  0.04145374, ...,  0.02785829,
       -0.04599191, -0.0236824 ], shape=(1536,), dtype=float32))
('26', '170', '부산광역시 동구', array([ 0.00968294,  0.02236298,  0.04267199, ...,  0.00309665,
       -0.02649185,  0.01100334], shape=(1536,), dtype=float32))
('26', '200', '부산광역시 영도구', array([ 0.0293182 , -0.01792667,  0.01659766, ...,  0.01293039,
       -0.01983525, -0.01057214], shape=(1536,), dtype=float32))
('26', '230', '부산광역시 부산진구', array([-0.01387175, -0.02141504,  0.04640868, ..., -0.00178341,
       -0.00562216, -0.0146063 ], shape=(1536,), dtype=float32))
('26', '260', '부산광역시 동래구', array([-0.0210779 , -0.00568671,  0.03346091, ...,  0.00684568,
       -0.02565199,  0.01063167], shape=(1536,), dtype=float32))
('26', '290', '부산광역시 남구', array([-0.01387733,  0.00988036,  0.03520696, ...,  0.0251585 ,
       -0.02310398, -0.01921908], shape=(1536,), dtype=float32))
('26', '320', '부산광역시 북구', array([-0.00601259,  0.02108097,  0.02663247, ...,  0.01510526,
       -0.01573234,  0.00291869], shape=(1536,), dtype=float32))
('26', '350', '부산광역시 해운대구', array([-0.00213143, -0.02595544,  0.04903988, ...,  0.01196899,
       -0.02578086, -0.02706117], shape=(1536,), dtype=float32))
('26', '380', '부산광역시 사하구', array([ 0.01375332, -0.00375394,  0.07529431, ...,  0.03598444,
       -0.01769457, -0.0133633 ], shape=(1536,), dtype=float32))
('26', '410', '부산광역시 금정구', array([ 0.01389557, -0.00028178,  0.04305613, ..., -0.00453368,
        0.00053871, -0.02416621], shape=(1536,), dtype=float32))
('26', '440', '부산광역시 강서구', array([-0.00285726,  0.00670532,  0.06862631, ...,  0.01657426,
       -0.05492886, -0.00729198], shape=(1536,), dtype=float32))
('26', '470', '부산광역시 연제구', array([ 0.02029237,  0.01212125,  0.06216371, ...,  0.01437846,
       -0.02984039,  0.00243638], shape=(1536,), dtype=float32))
('26', '500', '부산광역시 수영구', array([ 0.00619708,  0.00089952,  0.07328381, ...,  0.01559887,
       -0.02307011, -0.0296726 ], shape=(1536,), dtype=float32))
('26', '530', '부산광역시 사상구', array([ 0.03449064,  0.0243916 ,  0.05667007, ...,  0.03218229,
       -0.03345189, -0.01099353], shape=(1536,), dtype=float32))
('26', '710', '부산광역시 기장군', array([-0.01375082,  0.02162955,  0.04423074, ...,  0.01198708,
       -0.01475414, -0.00365685], shape=(1536,), dtype=float32))
('28', '000', '인천광역시 ', array([-0.07273455, -0.02502052,  0.03317536, ..., -0.00689351,
       -0.03086894,  0.01350902], shape=(1536,), dtype=float32))
('28', '110', '인천광역시 중구', array([-0.07193218, -0.02090126,  0.01577543, ..., -0.02476696,
       -0.03717886, -0.0072387 ], shape=(1536,), dtype=float32))
('28', '115', '인천광역시 중구영종출장', array([-0.01302919, -0.01379939,  0.02813363, ..., -0.03189905,
       -0.05639564,  0.02383336], shape=(1536,), dtype=float32))
('28', '116', '인천광역시 중구용유출장', array([-0.0554955 ,  0.02001607,  0.03601304, ...,  0.00384597,
       -0.03753439, -0.01223898], shape=(1536,), dtype=float32))
('28', '140', '인천광역시 동구', array([-0.04236605, -0.0220227 ,  0.0183239 , ..., -0.01930174,
       -0.03280021,  0.01492271], shape=(1536,), dtype=float32))
('28', '170', '인천광역시 남구', array([-0.06383471, -0.01254854,  0.03017397, ...,  0.00332872,
       -0.02390928, -0.00759618], shape=(1536,), dtype=float32))
('28', '177', '인천광역시 미추홀구', array([-0.05763924, -0.0665388 ,  0.02499364, ..., -0.03732411,
       -0.01754961,  0.00852528], shape=(1536,), dtype=float32))
('28', '185', '인천광역시 연수구', array([-0.04278696, -0.0449263 ,  0.03385845, ..., -0.02665453,
       -0.02434054, -0.01899217], shape=(1536,), dtype=float32))
('28', '200', '인천광역시 남동구', array([-0.0423326 , -0.01311019,  0.02304733, ...,  0.00447694,
       -0.02859541, -0.00443656], shape=(1536,), dtype=float32))
('28', '230', '인천광역시 북구', array([-0.06472433, -0.01720845,  0.0182929 , ..., -0.01723699,
       -0.01902537,  0.01007394], shape=(1536,), dtype=float32))
('28', '235', '인천광역시 북구계양출장', array([-0.02259191,  0.01677177,  0.02810105, ..., -0.02865641,
       -0.04162954,  0.00895235], shape=(1536,), dtype=float32))
('28', '237', '인천광역시 부평구', array([-0.05317156, -0.01065958,  0.03377638, ..., -0.02025028,
       -0.02458407, -0.00308273], shape=(1536,), dtype=float32))
('28', '245', '인천광역시 계양구', array([-0.04830498, -0.02512901,  0.02968608, ..., -0.02103849,
       -0.03359214, -0.00731844], shape=(1536,), dtype=float32))
('28', '260', '인천광역시 서구', array([-0.05977025, -0.01531636,  0.0355401 , ..., -0.00509427,
       -0.04892035, -0.00466056], shape=(1536,), dtype=float32))
('28', '265', '인천광역시 서구검단출장', array([-0.03574147,  0.02113977,  0.05354339, ..., -0.01976334,
       -0.04748706, -0.00628573], shape=(1536,), dtype=float32))
('28', '710', '인천광역시 강화군', array([-0.03112581,  0.00102737,  0.02133389, ..., -0.0295841 ,
       -0.04470949, -0.01096903], shape=(1536,), dtype=float32))
('28', '720', '인천광역시 옹진군', array([-0.05926817, -0.01199719,  0.01720623, ..., -0.00611652,
       -0.00668561,  0.00959263], shape=(1536,), dtype=float32))
('42', '150', '강원도 강릉시', array([-0.04686987, -0.0075844 ,  0.00314028, ...,  0.00782727,
       -0.03688233, -0.02132153], shape=(1536,), dtype=float32))
('50', '000', '제주특별자치도 ', array([ 0.0019531 ,  0.00284857,  0.01978069, ..., -0.02401695,
        0.02403991, -0.00504562], shape=(1536,), dtype=float32))
('50', '110', '제주특별자치도 제주시', array([ 0.02548048,  0.00996843, -0.00135441, ..., -0.0196748 ,
        0.01520967, -0.00342696], shape=(1536,), dtype=float32))
('50', '130', '제주특별자치도 서귀포시', array([ 0.02506413, -0.00461667,  0.00813208, ...,  0.01078838,
       -0.00875919, -0.02186229], shape=(1536,), dtype=float32))
('51', '150', '강원특별자치도 강릉시', array([-0.03872129, -0.01125157, -0.01259706, ..., -0.01709408,
       -0.02631386, -0.0206068 ], shape=(1536,), dtype=float32))

postgresql+psycopg2://postgres:***@localhost:5432/postgres

In [6]:
import numpy as np
import faiss

embeddings = np.array(embeddings).astype("float32")

dimension = embeddings.shape[1]
index = faiss.IndexFlatL2(dimension)
index.add(embeddings)

query = "부산 맛집 추천해줘."
query_emb = client.embeddings.create(
    model="text-embedding-3-small",
    input=query
).data[0].embedding
query_emb = np.array([query_emb], dtype="float32")

# FAISS 검색
D, I = index.search(query_emb, k=3)
print("\n[검색어]", query)
for rank, idx in enumerate(I[0]):
    print(f"{rank+1}위: {final_df.iloc[idx]['시도_시군구']} (거리: {D[0][rank]:.4f})")

[검색어] 부산 맛집 추천해줘.
1위: 부산광역시  (거리: 1.0685)
2위: 부산광역시 남구 (거리: 1.0717)
3위: 부산광역시 중구 (거리: 1.1368)